name: Rspec and Rubocop CI

on: [push,pull_request]

jobs:
  rubocop-test:
    runs-on: ubuntu-latest
    name: Rubocop
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install Gems
        run: bundle install
      - name: Run Rubocop
        run: bundle exec rubocop
  rspec-test:
    name: RSpec
    needs: rubocop-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install Gems
        run: bundle install
      - name: Build and test with rspec
        run: bundle exec rspec
